### ISSUE TITLE
use qualified names

### ISSUE THREAD

**Issue by c-cube** [LexiFi/landmarks#1]
I just tried landmarks on an experimental program of mine, and it is really nice: the web interface is convenient and it's really easy to set up, so thanks!

A small change that might be nice, when using `[@@@landmarks auto]`, would be to have function names qualified by their path from the name of the current module. For instance, in:

```ocaml
(* file A.ml *)

let x = …

module B = struct
  let y = …
end
```

we would have, in the trace, "A.x" and "A.B.y" instead of "x" and "y".

**Comment by mlasson** [comment]
Good idea, I'll do that.

**Comment by mlasson** [comment]
Note that the provided manually name will be also "qualified" (even if they are not identifier).
I could change this behavior if someone thinks it's a bad idea.
