### ISSUE TITLE
Weird counters for load(opcodes.ml) in the sample typecore.json

### ISSUE THREAD

**Issue by alainfrisch** [LexiFi/landmarks#2]
The provided sample `typecore.json` shows:

````
load(bytecomp/opcodes.ml)	30 396	151 744 080
````

i.e. 30396 calls and 151744080 CPU cycles.  I've been told (personal communication) that this landmark wraps the initialization for that compilation unit, so it should really be called at most once in a given process (as other `load(...)` landmark).

**Comment by alainfrisch** [comment]
Cf http://caml.inria.fr/mantis/view.php?id=5764 , same bug as the one we had while switching Bisect to ppx.

**Comment by mlasson** [comment]
That's a bug in the PPX extension. 

The names "__generated_landmark__1" is exported (because there's no opcodes.mli) and the module Opcodes is opened in some other file where "__generated_landmark__1" is overriden and used.
