### ISSUE TITLE
ppx dependencies woes; package split?

### ISSUE THREAD

**Issue by gasche** [LexiFi/landmarks#21]
I am considering using Landmarks for a project, but `opam install landmarks` wants to downgrade and recompile `ppxlib`, which is a red flag as most of the OCaml ppx ecosystem depends on `ppxlib` nowadays (I don't want to recompile all those dependencies, and I should not have to downgrade).

I think that there are two related problems here:

1. Landmarks has a strict dependency on `ocaml-migrate-parsetree < 2.0.0`; could this requirement be lifted in a new version of landmarks, that would make it compatible with the rest of the still-alive ppx ecosystem?

2. I don't actually plan to use landmarks ppx support, so I would prefer being able to install landmarks without dealing with all of that. Could the ppx support be proposed in a separate package `landmarks-ppx`, so that non-ppx users can easily install the software without having to pay for ppx maintainability woes?

I would be willing to help along the way, but not to do (2), which sounds easier but is also very boring packaging stuff. @mlasson, if you were motivated to implement (2), I could have a try at a PR to fix (1) in reciprocity -- unless this has already been done somewhere and I missed it, of course.

**Comment by mlasson** [comment]
> I am considering using Landmarks for a project, but opam install landmarks wants to downgrade and recompile ppxlib, which is a red flag as most of the OCaml ppx ecosystem depends on ppxlib nowadays (I don't want to recompile all those dependencies, and I should not have to downgrade).

I just made a PR to use ppxlib on gen_js_api ( https://github.com/LexiFi/gen_js_api/pull/149 ).
I think it is good for my ppxlib kung-fu to do 1 as well. I'll do 2 too.

**Comment by gasche** [comment]
Thanks! I'm happy to leave the work to you :-)

**Comment by mlasson** [comment]
Reopening because we should still split the package :).
