### ISSUE TITLE
Error with let operators

### ISSUE THREAD

**Issue by maroneze** [LexiFi/landmarks#28]
We're using Landmarks on Frama-C (when landmarks is installed, it is optionally enabled when building Frama-C), but a recent addition of a `let+` operator in our code results in an error:

```
Fatal error: exception (...): let operators are not supported before OCaml 4.08
Error: Error while running external preprocessor
Command line: /home/user/.opam/4.08.1/lib/landmarks/ppx/./ppx.exe --as-ppx '/tmp/camlppx2353e9' '/tmp/camlppxf2433e'
```

I tried using OCaml 4.08, but also 4.12, and I get the same error message mentioning OCaml < 4.08, so I'm assuming it's an issue with the error message and not my OCaml version.

I believe that fixing https://github.com/LexiFi/landmarks/issues/26 would fix this as well, but in case there's a simpler workaround for this issue in particular, it would be helpful. For now, we have to disable landmarks to be able to compile Frama-C.

**Comment by mlasson** [comment]
https://github.com/ocaml/opam-repository/pull/19274

**Comment by mlasson** [comment]
It should be good now !

**Comment by maroneze** [comment]
Thanks a lot! Indeed, I'm now able to recompile Frama-C with the new Landmarks installed, without any issues, if I don't explicitly enable the instrumentation.

However, there's something a bit odd going on, which didn't happen before: when I instrument the Frama-C build process using `OCAML_LANDMARKS=auto make` (as I used to do, after having added flags `-package landmarks -package landmarks-ppx` to the compilation of Frama-C), a few files have inexplicable compilation errors, mentioning missing constructors, such as:

```
File "src/plugins/dive/build.ml", line 50, characters 35-47:
50 |       method! vlval lval = f lval; SkipChildren
                                        ^^^^^^^^^^^^
Error: Unbound constructor SkipChildren
```

And :

```
File "src/plugins/wp/TacSequence.ml", line 62, characters 10-20:
62 |           Applicable
               ^^^^^^^^^^
Error: Unbound constructor Applicable
```

Note that these errors *only* happen when using `OCAML_LANDMARKS=auto make` and not simply `make`.

Also, I did not follow the new instructions (which mention the usage of `-ppxopt landmarks-ppx,--auto`), I just tried running the old setup; so that could be the reason.

However, if I disable the two affected plugins during `configure` (to avoid compiling those files), I am once again able to compile the instrumented Frama-C, and run it as I used to do (`OCAML_LANDMARKS=<options> bin/frama-c <files>`). This results in the full profiling tree, just as it did before. So, even if my instrumentation is incomplete or somehow incorrect, Landmarks still seems to work, except for those weird compilation errors. I'll investigate it further and try to get a minimal example; I'm mentioning it just in case.

By the way, a minor remark concerning the README.md, in the section `OCAMLPARAM`:

```
I=$(ocamlfind query landmarks),cma=landmarks.cma,cmxa=landmarks.cmxa,ppx=$(ocamlfind query landmarks)/ppx_landmarks,_"
```

I believe there is a missing `"` just after the initial `I=`, and I wonder if the second `$(ocamlfind query landmarks)` shouldn't be `$(ocamlfind query landmarks-ppx)` instead, since that's the directory containing `ppx_landmarks.*` files. Still, even after changing it, OCaml complains about `sh: line 1: $HOME/.opam/4.12.0/lib/landmarks-ppx/ppx_landmarks: No such file or directory`, so I wasn't able to try that method (and if I try adding an extension to match one of the existing files, it then complains about "Permission denied"; and the only executable file I see in that directory is `ppx.exe`, and in that case it says `too many input files`, so I have no idea what the actual value should be).

Anyway, thanks for the fast response and for improving Landmarks!

**Comment by mlasson** [comment]
> However, there's something a bit odd going on, which didn't happen before: when I instrument the Frama-C build process using `OCAML_LANDMARKS=auto make` (as I used to do, after having added flags `-package landmarks -package landmarks-ppx` to the compilation of Frama-C), a few files have inexplicable compilation errors, mentioning missing constructors, such as:
> 
> ```
> File "src/plugins/dive/build.ml", line 50, characters 35-47:
> 50 |       method! vlval lval = f lval; SkipChildren
>                                         ^^^^^^^^^^^^
> Error: Unbound constructor SkipChildren
> ```
> 
> And :
> 
> ```
> File "src/plugins/wp/TacSequence.ml", line 62, characters 10-20:
> 62 |           Applicable
>                ^^^^^^^^^^
> Error: Unbound constructor Applicable
> ```
> 
> Note that these errors _only_ happen when using `OCAML_LANDMARKS=auto make` and not simply `make`.

Ok, it may be due to one new features of the "auto" mode: it now automatically instrument the methods. 
The ppx rewrite `method f x = body` intro `method f x = Landmark.enter...; try let r = body in Landmark.exit ...; r with exn -> Landmark.exit; raise exn` probably it changes how the types are inferred. 

I would not be surprised if simply annotating the type of the constructors would solve your problems (SkipChildren : <insert the expected type>).

Also you can add "[@@@landmark "auto-off"]" at the beginning of the file to disable the automatic mode for this file. 

Or, better but more complicated, you could stop using the "OCAML_LANDMARKS=auto" and relies on the "--auto" option of the ppx.  It does the same thing but if you control the build system, you can use --auto on some files and stop using it on other files. 
(Of course, you could achieve the same thing by unsetting the environment variable, but that does not feel right). 

The OCAML_LANDMARKS controls both the behavior of ppx and the runtime. It was probably a bad idea.
Maybe, I should deprecate "auto" in "OCAML_LANDMARKS" to make the preprocessing independent of the environnement variables. 

> Also, I did not follow the new instructions (which mention the usage of `-ppxopt landmarks-ppx,--auto`), I just tried running the old setup; so that could be the reason.

It could help you indeed, but you will need not to add in on the "buggy" files. 

> However, if I disable the two affected plugins during `configure` (to avoid compiling those files), I am once again able to compile the instrumented Frama-C, and run it as I used to do (`OCAML_LANDMARKS=<options> bin/frama-c <files>`). This results in the full profiling tree, just as it did before. So, even if my instrumentation is incomplete or somehow incorrect, Landmarks still seems to work, except for those weird compilation errors. 

> I'll investigate it further and try to get a minimal example; I'm mentioning it just in case.

That would be great ! 

You should try with a method taking at least one argument and returning a constructor not in the current scope that could be guessed from type inference (of method! overloading probably adds a constraint on the return type ?). 

> By the way, a minor remark concerning the README.md, in the section `OCAMLPARAM`:
> ```
> I=$(ocamlfind query landmarks),cma=landmarks.cma,cmxa=landmarks.cmxa,ppx=$(ocamlfind query landmarks)/ppx_landmarks,_"
> ```
> I believe there is a missing `"` just after the initial `I=`, and I wonder if the second `$(ocamlfind query landmarks)` shouldn't be `$(ocamlfind query landmarks-ppx)` instead, since that's the directory containing `ppx_landmarks.*` files. Still, even after changing it, OCaml complains about `sh: line 1: $HOME/.opam/4.12.0/lib/landmarks-ppx/ppx_landmarks: No such file or directory`, so I wasn't able to try that method (and if I try adding an extension to match one of the existing files, it then complains about "Permission denied"; and the only executable file I see in that directory is `ppx.exe`, and in that case it says `too many input files`, so I have no idea what the actual value should be).

Since the migration to the ppxlib we are not shiping a standalone executable for the preprocessor.
I don't know if it would be is to build one and include it in the distribution. But the simplest fix would be to remove the paragraph about OCAMLPARAM from the README. :)

**Comment by maroneze** [comment]
Ok, I got some more information: in fact, in the 3 files where compilation fails, we are using constructors declared in a different module (which is never `open`ed), without prefixing them by the module name, and the reason they compile "normally" seems to be that, because the code is inside a class which `inherit`s from another class in the given module, then we get access to the constructors in the code (e.g., in the example I gave above, `SkipChildren` is declared in module `Cil`, and the code is inside a `object inherit Cil.cil_visitor`, so this `inherit` allows `SkipChildren` to be identified as `Cil.SkipChildren`). But somehow the PPX process seems to break this inheritance, and the constructor is not found. Prefixing the module name is necessary to ensure compilation succeeds in both cases. So, it doesn't seem related to Landmarks, and there is an easy workaround anyway.

**Comment by mlasson** [comment]
Here is a minimal example: 
```ocaml
module Test = struct
  module M = struct
    type t = A | B
  end

  class a =
    object
      method f = M.A
    end

  class b =
    object
      inherit a

      method! f = B
    end
end
```

**Comment by mlasson** [comment]
If you replace "method! f = B" by "method f = try B with exn -> raise exn" (which is half the rewriting done by the ppx) you get the same error.

We could fix the generated code by adding "type variables" to guide the type inference, eg rewrite into: 
```ocaml
method! f : 'a = try (B : 'a) with exn -> raise exn
```

I'll create an issue.
