### ISSUE TITLE
broken viewer?

### ISSUE THREAD

**Issue by samoht** [LexiFi/landmarks#32]
It seems that the online viewer cannot read the generated JSON files anymore. Is this expected? Thanks for the nice tool :-)

**Comment by nojb** [comment]
cc @mlasson

**Comment by Armael** [comment]
Just stumbling on this as well. Ping? :-)

**Comment by mlasson** [comment]
Ok; I'll try to fix this situation as soon as possible.

**Comment by anton-trunov** [comment]
I also just ran into this. Thanks for the cool tool!

**Comment by jboillot** [comment]
Hello!
Just so future visitors know, I have forked the viewer project and added dirty fixes to make it work again: https://github.com/jboillot/landmarks-viewer/tree/hotfix/make-it-work

**Comment by jboillot** [comment]
Until a better solution is found, here is a working viewer: [https://jerome-boillot.com/landmarks-viewer/](https://jerome-boillot.com/landmarks-viewer/).

**Comment by mlasson** [comment]
I deployed a new viewer just after merging https://github.com/jboillot/landmarks-viewer/tree/hotfix/make-it-work. 
Thanks again @jboillot
