### ISSUE TITLE
Reuse ppx instrumentation for print/debugging?

### ISSUE THREAD

**Issue by maroneze** [LexiFi/landmarks#39]
I have a new OCaml user that wants to track a sequence of function calls (just to better understand the code), and the easiest way seems to be to just add calls to printf at each function entry and exit (or even just entry). But manually doing so is a bit annoying.

I wonder if Landmark's PPX could somehow enable this behavior: with a simple annotation `[@landmark "something"]` in each function to be tracked, instead of incrementing the counters, just print a message such as "entering function f" or something... is there something like this?

**Comment by nojb** [comment]
Hello; no, `landmarks` does not have this kind of tracing functionality (and, as far as I know, there are no plans to go in this direction).

However, implementing this from scratch should not be very difficult; in fact a quick search yielded https://github.com/c-cube/ocaml-trace; may be worth checking it out.

cc @mlasson

**Comment by maroneze** [comment]
Thanks for the recommendation, I tested it quickly and it seems to do most of what I wanted (except that I now noticed that I'd need a `%trace` syntax for class methods as well...). I'll do some more testing and recommend it to our OCaml interns, it's helpful for learning.
