### ISSUE TITLE
Errors with some OCAML_LANDMARKS options

### ISSUE THREAD

**Issue by maroneze** [LexiFi/landmarks#7]
I tried both the OPAM 1.0 version and git-pinning as indicated, and got the same result in both cases.

After compiling the example program, I tried several options, but got some errors:

    $ OCAML_LANDMARKS=debug ./prog
    [LANDMARKS] Unknown option 'debug'.

    $ OCAML_LANDMARKS=on ./prog
    [LANDMARKS] Unknown option 'on'.

    $ OCAML_LANDMARKS=output=/tmp/file.txt ./prog
    [LANDMARKS] The argument '/tmp/file.txt' in not valid for the option 'output'.

    $ OCAML_LANDMARKS=output=temporary:/tmp/ ./prog
    [LANDMARKS] The argument 'temporary:/tmp/' in not valid for the option 'output'.

This also happens when adding simple and double quotes to the names of the file or directory in the latter cases.

The other options I tried (off, format=json, auto, etc.) all seem to work, so I don't know if I'm doing something wrong.

**Comment by mlasson** [comment]
Thanks for the report !

The "debug" case was indeed forgetten (fixed in c0458e3). 

All the other cases were already ok on the dev version (I think something went wrong with your tests).

**Comment by maroneze** [comment]
Thanks, and indeed, a missing dependency was not forcing recompilation in my tests, so I was still using the released 1.0 and not the dev version.
