### ISSUE TITLE
Clarification about recursive call count

### ISSUE THREAD

**Issue by maroneze** [LexiFi/landmarks#8]
I'd like to suggest a clarification about recursive function calls to the Github README page (which I find very useful as reference for new users): I think it could be useful to add something related to the call counters, e.g. that they may not correspond to the "intuitive" notion when using PPX-generated landmarks inside recursive call nests.

For instance, in the following program:

```
let[@landmark] rec f n =
  if n <= 1 then 1 else g (n-1)
and[@landmark] g n =
  f (n-1)

let[@landmark] rec h n =
  if n <= 1 then 1 else h (n-1)

let () =
  Format.printf "g = %d@." (g 10);
  Format.printf "h = %d@." (h 10);
```

The report says that functions `g` and `h` were both called once (`1 calls`), and `f` seems to not have been called.

This is not very intuitive (I'd have expected all functions to have several calls each) and can lead to some confusion. For instance, in my real-world case, I had a mutually recursive function which was not directly called, so it was not being reported, even though the function was indirectly called by another one. A small clarification about that could help beginners.

**Comment by mlasson** [comment]
You are right, thank you for the report ! I added a small paragraph in the readme.
